### ISSUE TITLE
"Undefined symbols for architecture x86_64" on mac os

### ISSUE THREAD

**Issue by kal247** [ChisholmKyle/PosixMachTiming#2]
Hello,

I have the following error when trying to compile on mac os 10.11 :

`clang -std=c99 timing*.c -o timing_testp && ./timing_testclang`

```
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _clock_nanosleep_abstime in timing_mach-0abf2d.o
      _itimer_start in timing_mach-0abf2d.o
      _main in timing_test-f15b24.o
  "_timing_mach_init", referenced from:
      _main in timing_test-f15b24.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kal247** [comment]
Bug not related to PosixMachTiming
